In [ ]:
import pandas as pd
import numpy as np
import matplotlib

In [ ]:
credits_immo_csv = pd.read_csv("Data_Vis/credit_immo.csv")
credits_immo_csv.head()

In [ ]:
credits_immo_json = pd.read_json("Data_Vis/credit_immo.json")
credits_immo_json.head()

In [ ]:
credits_immo_xls = pd.read_excel("Data_Vis/credit_immo.xls")
credits_immo_xls.head()

In [ ]:
credits_immo_csv = pd.read_csv("Data_Vis/credit_immo.csv")
credits_immo_csv.head()

In [ ]:
credits_immo_csv

In [ ]:
df = pd.DataFrame(index[])

### 3.Traitement des données

In [17]:
import pandas as pd 
import numpy as np
from sklearn.impute import SimpleImputer

In [18]:
df = pd.read_csv("Data_Vis/credit_immo.csv")
credits_immo_csv.head()

ID_NOM  Niv_Etude_Bac  age contrat_de_travail  Salaire  dette_anterieure  \
0      jean            3.0   45                CDI    40000              4000   
1   VANESSA            5.0   28                CDI    30500              1320   
2  TARCISSE            0.0   55                CDI    28000             40000   
3   TIBAULT            4.0   23                CDD    15000                 0   
4     GILES            0.0   33                CDD    27000              3000   

  etat_civile  apport  enfant_a_Charge Solvable  
0           M     0.3              3.0      OUI  
1           M     0.1              0.0      OUI  
2           C     0.0              0.0      NON  
3           M     0.1              NaN      OUI  
4           C     0.1              2.0      NON

In [112]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])
X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
imp_mean.transform(X)

array([[ 7. ,  2. ,  3. ],
       [ 4. ,  3.5,  6. ],
       [10. ,  3.5,  9. ]])

In [111]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
num_col = credits_immo_csv.select_dtypes(include="number").columns
im = SimpleImputer()
imputed = im.fit_transform(credits_immo_csv[num_col])
print(imputed)



[[ 3.00000000e+00  4.50000000e+01  4.00000000e+04  4.00000000e+03
   3.00000000e-01  3.00000000e+00]
 [ 5.00000000e+00  2.80000000e+01  3.05000000e+04  1.32000000e+03
   1.00000000e-01  0.00000000e+00]
 [ 0.00000000e+00  5.50000000e+01  2.80000000e+04  4.00000000e+04
   0.00000000e+00  0.00000000e+00]
 [ 4.00000000e+00  2.30000000e+01  1.50000000e+04  0.00000000e+00
   1.00000000e-01  1.33333333e+00]
 [ 0.00000000e+00  3.30000000e+01  2.70000000e+04  3.00000000e+03
   1.00000000e-01  2.00000000e+00]
 [ 0.00000000e+00  4.10000000e+01  4.00000000e+04  1.00000000e+03
   0.00000000e+00  4.00000000e+00]
 [-1.00000000e+00  2.90000000e+01  5.00000000e+04  3.00000000e+03
   0.00000000e+00  0.00000000e+00]
 [-3.00000000e+00  2.40000000e+01  2.90000000e+04  5.00000000e+03
   0.00000000e+00  0.00000000e+00]
 [ 1.44444444e+00  2.60000000e+01  4.40000000e+04  0.00000000e+00
   1.00000000e-01  1.00000000e+00]
 [ 3.00000000e+00  3.70000000e+01  4.58000000e+04  2.00000000e+03
   2.00000000e-01  2.0000

In [110]:
colomns_categorie = ["contrat_de_travail", "etat_civile", "Solvable"]
def encoder(colomns):
    le = preprocessing.LabelEncoder()
    le.fit(credits_immo_csv[colomns])
    list(le.classes_)
    print(le.transform(credits_immo_csv[colomns]))
for i in colomns_categorie:
    print(i)
    encoder(i)

contrat_de_travail
[1 1 1 0 0 3 1 3 1 1 1 0 3 1 0 2 1 1 1]
etat_civile
[1 1 0 1 0 1 0 0 1 1 1 0 1 1 0 1 1 1 1]
Solvable
[1 1 0 1 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1]


ID_NOM                 object
Niv_Etude_Bac         float64
age                     int64
contrat_de_travail     object
Salaire                 int64
dette_anterieure        int64
etat_civile            object
apport                float64
enfant_a_Charge       float64
Solvable               object
dtype: object

In [71]:
from sklearn.model_selection import train_test_split

In [104]:
x = credits_immo_csv.iloc[:50]
y = credits_immo_csv.iloc[50:]
x_test, x_train, y_test, y_train = train_test_split(x,y,test_size=0.8, random_state=3)


ValueError: Found input variables with inconsistent numbers of samples: [19, 0]

In [95]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0],[0, 0],[1, 1],[1, 1]]
scaler = StandardScaler()
scaler.fit(data)
scaler.transform(data)

print(scaler.transform([[2, 2]]))

[[3. 3.]]


In [1]:
scaler = StandardScaler()
scaler.fit(credits_immo_csv)

NameError: name 'StandardScaler' is not defined

In [4]:
# 1.Déploiement de l’environnement
import pandas as pd 
import numpy as np
import matplotlib
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 2.Sources de données : Manipulation
credits_immo_csv = pd.read_csv("Data_Vis/credit_immo.csv")
credits_immo_json = pd.read_json("Data_Vis/credit_immo.json")
credits_immo_xls = pd.read_excel("Data_Vis/credit_immo.xls")


# 3.Traitement des données
#3.2
df = pd.read_csv("Data_Vis/credit_immo.csv")
#3.3
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
num_col = credits_immo_csv.select_dtypes(include="number").columns
im = SimpleImputer()
imputed = im.fit_transform(credits_immo_csv[num_col])
#3.4
colomns_categorie = ["contrat_de_travail", "etat_civile", "Solvable"]
def encoder(colomns):
    le = preprocessing.LabelEncoder()
    le.fit(credits_immo_csv[colomns])
    list(le.classes_)
    #print(le.transform(credits_immo_csv[colomns]))
for i in colomns_categorie:
    #print(i)
    encoder(i)

#3.5
train, test = train_test_split(df, test_size=0.2)

#3.6


In [8]:
scaler = StandardScaler()
scaler.fit(credits_immo_csv[num_col])
scaler.mean_
scaler.transform(credits_immo_csv[num_col])

array([[ 0.56918094,  0.69964472, -0.15939982, -0.34223088,  1.24354001,
         1.29099445],
       [ 1.30098501, -0.77738303, -0.61392855, -0.45846885, -0.33161067,
        -1.03279556],
       [-0.52852516,  1.56848458, -0.73354137,  1.21917467, -1.11918601,
        -1.03279556],
       [ 0.93508297, -1.21180295, -1.35552804, -0.51572038, -0.33161067,
                nan],
       [-0.52852516, -0.3429631 , -0.7813865 , -0.38560325, -0.33161067,
         0.51639778],
       [-0.52852516,  0.35210878, -0.15939982, -0.47234801, -1.11918601,
         2.06559112],
       [-0.89442719, -0.69049904,  0.31905146, -0.38560325, -1.11918601,
        -1.03279556],
       [-1.62623126, -1.12491897, -0.68569624, -0.2988585 , -1.11918601,
        -1.03279556],
       [        nan, -0.951151  ,  0.03198069, -0.51572038, -0.33161067,
        -0.25819889],
       [ 0.56918094,  0.00457284,  0.11810192, -0.42897563,  0.45596467,
         0.51639778],
       [ 0.20327891,  0.2652248 ,  0.79750275, -0.